/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#include "STM32F103x8.h"
#include "stm32f103x8_gpio_driver.h"
#include "stm32f103x8_EXTI_driver.h"


 uint8_t IRQ_Flag = 0;
 uint32_t CONTROL_REG = 0;
 uint32_t IPSR_REG = 0;

 enum Access_Level{
	 Privillaged,
	 UnPrivillaged
 };

 void NMI_Handler(){
	 while(1);

 }
 void MemManage_Handler(){
	 while(1);

 }
 void BusFault_Handler(){
	 while(1);

 }

 void UsageFault_Handler()
 {
	 while(1);

 }
 void switch_CPUAccessLevel(enum Access_Level level)
 {
	 switch(level)
	 {
	 case Privillaged:
		 __asm("mrs r3,CONTROL \n\t"
				 "lsr r3,r3,#0x1 \n\t"
				 "lsl r3,r3,#0x1 \n\t"
						"msr CONTROL,r3" );
		 break;
	 case UnPrivillaged:
		 __asm("mrs r3,CONTROL \n\t"
			   "orr r3,r3,#0x1 \n\t"
				"msr CONTROL,r3" );
		 break;
	 default:
		 break;
	 }
	 //read the nPRIV (bit 0) into a register
	 //set the register
	 //str it nPRIV
 }

void EXTI9_CALLBACK(void)
{
	IRQ_Flag = 1;
	switch_CPUAccessLevel(Privillaged);
	__asm("mrs %[OUT0],IPSR"
				:[OUT0]"=r"(IPSR_REG));
}

int main(void)
{
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
	//switch_CPUAccessLevel(UnPrivillaged);

	//Set EXTI Configuration
	EXTI_PinConfig_t EXTIConfig;
	EXTIConfig.EXTI_PIN = EXTI9PB9;
	EXTIConfig.Trigger_Case = EXTI_Trigger_RISING;
	EXTIConfig.P_IRQ_CallBack = EXTI9_CALLBACK;
	EXTIConfig.IRQ_EN = EXTI_IRQ_Enable;
	MCAL_EXTI_GPIO_Init(&EXTIConfig);
	switch_CPUAccessLevel(UnPrivillaged);
//
	IRQ_Flag = 1;
	__asm("nop");
	__asm("nop");
	__asm("nop");
	__asm("mrs %[OUT0],CONTROL"
			:[OUT0]"=r"(CONTROL_REG));
	__asm("nop");
	__asm("nop");
	__asm("nop");

	while (1)
	{
		if(IRQ_Flag)
		{
			IRQ_Flag = 0;
		}
		else { /* Misra */ }
	}


}
