################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Core/Src/CortexMX_OS_porting.c \
../Core/Src/DistanceToSpeed.c \
../Core/Src/MYRTOS_FIFO.c \
../Core/Src/Scheduler.c \
../Core/Src/SysTick.c \
../Core/Src/main.c \
../Core/Src/stm32f1xx_hal_msp.c \
../Core/Src/stm32f1xx_it.c \
../Core/Src/syscalls.c \
../Core/Src/sysmem.c \
../Core/Src/system_stm32f1xx.c 

OBJS += \
./Core/Src/CortexMX_OS_porting.o \
./Core/Src/DistanceToSpeed.o \
./Core/Src/MYRTOS_FIFO.o \
./Core/Src/Scheduler.o \
./Core/Src/SysTick.o \
./Core/Src/main.o \
./Core/Src/stm32f1xx_hal_msp.o \
./Core/Src/stm32f1xx_it.o \
./Core/Src/syscalls.o \
./Core/Src/sysmem.o \
./Core/Src/system_stm32f1xx.o 

C_DEPS += \
./Core/Src/CortexMX_OS_porting.d \
./Core/Src/DistanceToSpeed.d \
./Core/Src/MYRTOS_FIFO.d \
./Core/Src/Scheduler.d \
./Core/Src/SysTick.d \
./Core/Src/main.d \
./Core/Src/stm32f1xx_hal_msp.d \
./Core/Src/stm32f1xx_it.d \
./Core/Src/syscalls.d \
./Core/Src/sysmem.d \
./Core/Src/system_stm32f1xx.d 


# Each subdirectory must supply rules for building sources it contributes
Core/Src/CortexMX_OS_porting.o: ../Core/Src/CortexMX_OS_porting.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F103xB -DDEBUG -c -I../Core/Inc -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/STM32F1xx_HAL_Driver/Inc" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/STM32F1xx_HAL_Driver/Inc/Legacy" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Inc" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Src" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Inc" -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/CortexMX_OS_porting.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Core/Src/DistanceToSpeed.o: ../Core/Src/DistanceToSpeed.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F103xB -DDEBUG -c -I../Core/Inc -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/STM32F1xx_HAL_Driver/Inc" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/STM32F1xx_HAL_Driver/Inc/Legacy" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Inc" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Src" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Inc" -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/DistanceToSpeed.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Core/Src/MYRTOS_FIFO.o: ../Core/Src/MYRTOS_FIFO.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F103xB -DDEBUG -c -I../Core/Inc -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/STM32F1xx_HAL_Driver/Inc" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/STM32F1xx_HAL_Driver/Inc/Legacy" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Inc" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Src" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Inc" -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/MYRTOS_FIFO.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Core/Src/Scheduler.o: ../Core/Src/Scheduler.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F103xB -DDEBUG -c -I../Core/Inc -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/STM32F1xx_HAL_Driver/Inc" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/STM32F1xx_HAL_Driver/Inc/Legacy" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Inc" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Src" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Inc" -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/Scheduler.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Core/Src/SysTick.o: ../Core/Src/SysTick.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F103xB -DDEBUG -c -I../Core/Inc -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/STM32F1xx_HAL_Driver/Inc" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/STM32F1xx_HAL_Driver/Inc/Legacy" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Inc" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Src" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Inc" -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/SysTick.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Core/Src/main.o: ../Core/Src/main.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F103xB -DDEBUG -c -I../Core/Inc -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/STM32F1xx_HAL_Driver/Inc" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/STM32F1xx_HAL_Driver/Inc/Legacy" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Inc" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Src" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Inc" -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/main.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Core/Src/stm32f1xx_hal_msp.o: ../Core/Src/stm32f1xx_hal_msp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F103xB -DDEBUG -c -I../Core/Inc -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/STM32F1xx_HAL_Driver/Inc" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/STM32F1xx_HAL_Driver/Inc/Legacy" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Inc" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Src" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Inc" -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/stm32f1xx_hal_msp.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Core/Src/stm32f1xx_it.o: ../Core/Src/stm32f1xx_it.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F103xB -DDEBUG -c -I../Core/Inc -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/STM32F1xx_HAL_Driver/Inc" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/STM32F1xx_HAL_Driver/Inc/Legacy" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Inc" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Src" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Inc" -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/stm32f1xx_it.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Core/Src/syscalls.o: ../Core/Src/syscalls.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F103xB -DDEBUG -c -I../Core/Inc -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/STM32F1xx_HAL_Driver/Inc" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/STM32F1xx_HAL_Driver/Inc/Legacy" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Inc" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Src" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Inc" -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/syscalls.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Core/Src/sysmem.o: ../Core/Src/sysmem.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F103xB -DDEBUG -c -I../Core/Inc -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/STM32F1xx_HAL_Driver/Inc" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/STM32F1xx_HAL_Driver/Inc/Legacy" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Inc" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Src" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Inc" -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/sysmem.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Core/Src/system_stm32f1xx.o: ../Core/Src/system_stm32f1xx.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F103xB -DDEBUG -c -I../Core/Inc -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/STM32F1xx_HAL_Driver/Inc" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/STM32F1xx_HAL_Driver/Inc/Legacy" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Inc" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Src" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Drivers/CMSIS/Include" -I"D:/KS_ES/codes/Learn_In_Depth_KS/Drivers/STM32F103x8/Final_GP_V22/Core/Inc" -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/system_stm32f1xx.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

